apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    io.kompose.service: todo-web-application
  name: todo-web-application
spec: 
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-web-application
  template: 
    metadata: 
      labels: 
        io.kompose.service: todo-web-application
    spec: 
      containers: 
      - env: 
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: todo-web-app-config
              key: RDS_DB_NAME
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: todo-web-app-config
              key: RDS_HOSTNAME
        - name: RDS_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: todo-web-app-secret
              key: RDS_PASSWORD
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-web-app-config
              key: RDS_PORT
        - name: RDS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: todo-web-app-config
              key: RDS_USERNAME          
        image: "saurabhkumardocker/todo-web-application-mysql:0.0.1-SNAPSHOT"
        name: todo-web-application
        ports: 
          - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    io.kompose.service: todo-web-application
  name: todo-web-application
spec: 
  type: LoadBalancer
  ports: 
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector: 
    io.kompose.service: todo-web-application